name:                cis194-spring13
version:             0.1.0.0
github:              "mistwave/cis194-spring13"
license:             BSD3
author:              "Yifu Duan"
maintainer:          "@mistwave"
copyright:           "2022 Yifu Duan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cis194-spring13#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cis194-spring13-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cis194-spring13

tests:
  cis194-spring13-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cis194-spring13
    - hspec
